### ISSUE TITLE
requests and responses get reported 8 times - the same message

### ISSUE THREAD

**Issue by ABHammad** [reportportal/logger-java-rest-assured#25]
**Describe the bug**
the rest assured request/response is getting reported 8 times, which is messy to filter a lot of logs are duplicated

**Steps to Reproduce**
1. add logger-java-rest-assured to the project
2. run junit5 test (rest assured) by mvn command (run in parallel)
3. check reportportal 

**Expected behavior**
it should logs messages just one time as it is called only one time 

**Actual behavior**
messages reported 8 times 

**Dependency versions**
<dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-rest-assured</artifactId>
            <version>5.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>5.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.22.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.22.1</version>
        </dependency>

**Comment by ABHammad** [comment]
@HardNorth 
here is the server version
API Service: 5.10.1;Index Service: 5.10.1;Jobs Service: 5.10.0;Authorization Service: 5.10.0;Service UI: 5.10.0;

**Comment by HardNorth** [comment]
@ABHammad Can you show how this looks, take a screenshot?

**Comment by ABHammad** [comment]
<img width="1362" alt="Screenshot 2024-02-13 at 13 06 22" src="https://github.com/reportportal/logger-java-rest-assured/assets/19577129/3972217b-87bd-4848-b7fa-f956e10eee98">

and there are still few messages more the same data

**Comment by HardNorth** [comment]
Duplicate: https://github.com/reportportal/reportportal/issues/2148
