### ISSUE TITLE
How to mask specific data in a JSON response

### ISSUE THREAD

**Issue by vfalco02** [reportportal/logger-java-rest-assured#28]
Pretty novice in Java and I'm just trying to figure out how to mask sensitive data in my requests/responses so that they are not visible in ReportPortal.

Example:
```
{
    "username": "joetester",
    "password": "*****"
}

**Comment by HardNorth** [comment]
@vfalco02 You should extend or create your own content prettier and configure it as said here, where you can cut whatever data you want: https://github.com/reportportal/logger-java-rest-assured?tab=readme-ov-file#sanitize-request--response-data
